import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Js Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h4 className={styles.title}>
          Demo For Renderings
        </h4>
        <ul>
          <li className={styles.subtitle}>
            <Link href='/ssg'><a>Static Site Generation (SSG) </a></Link>
          </li>
          <li className={styles.subtitle}>
            <Link href='/isr'><a>Incremental Static Regeneration (ISR) </a></Link>
          </li>
          <li className={styles.subtitle}>
            <Link href='/ssr'><a>Server Side Redering (SSR) </a></Link>
          </li>
          <li className={styles.subtitle}>
            <Link href='/csr'><a>Client Side Rendering (CSR) </a></Link>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
